### ISSUE TITLE
Liquid generators use too much liquids

### ISSUE THREAD

**Issue by Timarrr** [XZimur/NoiTech#23]
Fuel generators use not 10 fuel/sec, but nearly 36 fuel/sec. Pls fix it

**Comment by XZimur** [comment]
It is supposed to consume 36 fuel/sec.
This is a bug in the game, not in the mod.
And yes, i can fix this by doing it on mod side but this is lots of work just for 3 numbers.

**Comment by Timarrr** [comment]
You can Just set the consume nearly 3.333333...
